
runtime: nodejs
env: flex

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

env_variables:
  MONGODB_URI: 'mongodb://dennis:dennis@ds237717.mlab.com:37717/fcc-url-shortener-micoservice'
